[2025-01-16T07:40:41.447+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-16T07:40:41.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.extract_data manual__2025-01-16T07:40:34.892378+00:00 [queued]>
[2025-01-16T07:40:41.525+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.extract_data manual__2025-01-16T07:40:34.892378+00:00 [queued]>
[2025-01-16T07:40:41.535+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-16T07:40:41.564+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): extract_data> on 2025-01-16 07:40:34.892378+00:00
[2025-01-16T07:40:41.572+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-16T07:40:41.572+0000] {standard_task_runner.py:63} INFO - Started process 1414 to run task
[2025-01-16T07:40:41.586+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'extract_data', 'manual__2025-01-16T07:40:34.892378+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpka4fwzli']
[2025-01-16T07:40:41.591+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask extract_data
[2025-01-16T07:40:41.697+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.extract_data manual__2025-01-16T07:40:34.892378+00:00 [running]> on host airflow-scheduler
[2025-01-16T07:40:41.849+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T07:40:34.892378+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T07:40:34.892378+00:00'
[2025-01-16T07:40:41.851+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-16T07:40:41.863+0000] {base.py:84} INFO - Using connection ID 'spark_main' for task execution.
[2025-01-16T07:40:41.865+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /dags/resources/extract.py
[2025-01-16T07:40:42.182+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-01-16T07:40:42.184+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-16T07:40:42.185+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-01-16T07:40:42.189+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-16T07:40:44.038+0000] {spark_submit.py:641} INFO - 25/01/16 07:40:44 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-16T07:40:44.488+0000] {spark_submit.py:641} INFO - python3: can't open file '/dags/resources/extract.py': [Errno 2] No such file or directory
[2025-01-16T07:40:44.498+0000] {spark_submit.py:641} INFO - 25/01/16 07:40:44 INFO ShutdownHookManager: Shutdown hook called
[2025-01-16T07:40:44.500+0000] {spark_submit.py:641} INFO - 25/01/16 07:40:44 INFO ShutdownHookManager: Deleting directory /tmp/spark-52a84f0f-8008-4891-b9b6-6960835a17fd
[2025-01-16T07:40:44.539+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-16T07:40:44.551+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /dags/resources/extract.py. Error code is: 2.
[2025-01-16T07:40:44.567+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL, task_id=extract_data, run_id=manual__2025-01-16T07:40:34.892378+00:00, execution_date=20250116T074034, start_date=20250116T074041, end_date=20250116T074044
[2025-01-16T07:40:44.585+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task extract_data (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /dags/resources/extract.py. Error code is: 2.; 1414)
[2025-01-16T07:40:44.612+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-16T07:40:44.638+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-16T07:40:44.644+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
