[2025-01-16T11:18:31.464+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-16T11:18:31.495+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-16T11:18:11.341004+00:00 [queued]>
[2025-01-16T11:18:31.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-16T11:18:11.341004+00:00 [queued]>
[2025-01-16T11:18:31.504+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-16T11:18:31.517+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_data> on 2025-01-16 11:18:11.341004+00:00
[2025-01-16T11:18:31.521+0000] {standard_task_runner.py:63} INFO - Started process 6273 to run task
[2025-01-16T11:18:31.524+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'load_data', 'manual__2025-01-16T11:18:11.341004+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpd0cex_dc']
[2025-01-16T11:18:31.525+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask load_data
[2025-01-16T11:18:31.572+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.load_data manual__2025-01-16T11:18:11.341004+00:00 [running]> on host airflow-scheduler
[2025-01-16T11:18:31.655+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T11:18:11.341004+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T11:18:11.341004+00:00'
[2025-01-16T11:18:31.656+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-16T11:18:31.657+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-16T11:18:31.658+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /spark-scripts/resources/load.py']
[2025-01-16T11:18:31.666+0000] {subprocess.py:86} INFO - Output:
[2025-01-16T11:18:33.271+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-16T11:18:33.271+0000] {subprocess.py:93} INFO -   File "/spark-scripts/resources/load.py", line 126, in <module>
[2025-01-16T11:18:33.272+0000] {subprocess.py:93} INFO -     load()
[2025-01-16T11:18:33.272+0000] {subprocess.py:93} INFO -   File "/spark-scripts/resources/load.py", line 80, in load
[2025-01-16T11:18:33.273+0000] {subprocess.py:93} INFO -     transactions_df['quantity'] = transactions_df['quantity'].astype('int64')
[2025-01-16T11:18:33.273+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5815, in astype
[2025-01-16T11:18:33.273+0000] {subprocess.py:93} INFO -     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
[2025-01-16T11:18:33.274+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 418, in astype
[2025-01-16T11:18:33.274+0000] {subprocess.py:93} INFO -     return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
[2025-01-16T11:18:33.274+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 327, in apply
[2025-01-16T11:18:33.275+0000] {subprocess.py:93} INFO -     applied = getattr(b, f)(**kwargs)
[2025-01-16T11:18:33.275+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 591, in astype
[2025-01-16T11:18:33.275+0000] {subprocess.py:93} INFO -     new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
[2025-01-16T11:18:33.276+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/dtypes/cast.py", line 1309, in astype_array_safe
[2025-01-16T11:18:33.276+0000] {subprocess.py:93} INFO -     new_values = astype_array(values, dtype, copy=copy)
[2025-01-16T11:18:33.276+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/dtypes/cast.py", line 1257, in astype_array
[2025-01-16T11:18:33.276+0000] {subprocess.py:93} INFO -     values = astype_nansafe(values, dtype, copy=copy)
[2025-01-16T11:18:33.277+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/dtypes/cast.py", line 1168, in astype_nansafe
[2025-01-16T11:18:33.277+0000] {subprocess.py:93} INFO -     return astype_float_to_int_nansafe(arr, dtype, copy)
[2025-01-16T11:18:33.277+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/dtypes/cast.py", line 1213, in astype_float_to_int_nansafe
[2025-01-16T11:18:33.277+0000] {subprocess.py:93} INFO -     raise IntCastingNaNError(
[2025-01-16T11:18:33.278+0000] {subprocess.py:93} INFO - pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
[2025-01-16T11:18:33.463+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-16T11:18:33.464+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-16T11:18:33.473+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-16T11:18:33.481+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL, task_id=load_data, run_id=manual__2025-01-16T11:18:11.341004+00:00, execution_date=20250116T111811, start_date=20250116T111831, end_date=20250116T111833
[2025-01-16T11:18:33.493+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task load_data (Bash command failed. The command returned a non-zero exit code 1.; 6273)
[2025-01-16T11:18:33.502+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-16T11:18:33.524+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-16T11:18:33.529+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
