[2025-01-16T05:04:09.086+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-16T05:04:09.115+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.extract_data manual__2025-01-16T05:04:07.291808+00:00 [queued]>
[2025-01-16T05:04:09.123+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.extract_data manual__2025-01-16T05:04:07.291808+00:00 [queued]>
[2025-01-16T05:04:09.124+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-16T05:04:09.134+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2025-01-16 05:04:07.291808+00:00
[2025-01-16T05:04:09.138+0000] {standard_task_runner.py:63} INFO - Started process 5315 to run task
[2025-01-16T05:04:09.142+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'extract_data', 'manual__2025-01-16T05:04:07.291808+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpg1sao73y']
[2025-01-16T05:04:09.144+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask extract_data
[2025-01-16T05:04:09.190+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.extract_data manual__2025-01-16T05:04:07.291808+00:00 [running]> on host airflow-scheduler
[2025-01-16T05:04:09.261+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T05:04:07.291808+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T05:04:07.291808+00:00'
[2025-01-16T05:04:09.262+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-16T05:04:09.263+0000] {logging_mixin.py:188} INFO - Extracting data from PostgreSQL...
[2025-01-16T05:04:09.264+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-16T05:04:09.265+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL.py", line 10, in extract
    return extract_data()
  File "/opt/airflow/dags/resources/extract.py", line 51, in extract_data
    products_df = pl.read_database(products, connection_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/io/database.py", line 93, in read_database
    return _read_sql_connectorx(
  File "/home/airflow/.local/lib/python3.10/site-packages/polars/io/database.py", line 120, in _read_sql_connectorx
    raise ImportError(
ImportError: connectorx is not installed. Please run `pip install connectorx>=0.3.1`.
[2025-01-16T05:04:09.278+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL, task_id=extract_data, run_id=manual__2025-01-16T05:04:07.291808+00:00, execution_date=20250116T050407, start_date=20250116T050409, end_date=20250116T050409
[2025-01-16T05:04:09.287+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task extract_data (connectorx is not installed. Please run `pip install connectorx>=0.3.1`.; 5315)
[2025-01-16T05:04:09.315+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-16T05:04:09.332+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-16T05:04:09.336+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
