[2025-01-16T07:45:10.358+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-16T07:45:10.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.extract_data manual__2025-01-16T07:45:05.069711+00:00 [queued]>
[2025-01-16T07:45:10.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.extract_data manual__2025-01-16T07:45:05.069711+00:00 [queued]>
[2025-01-16T07:45:10.400+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-16T07:45:10.419+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): extract_data> on 2025-01-16 07:45:05.069711+00:00
[2025-01-16T07:45:10.424+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-16T07:45:10.424+0000] {standard_task_runner.py:63} INFO - Started process 821 to run task
[2025-01-16T07:45:10.430+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'extract_data', 'manual__2025-01-16T07:45:05.069711+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmprijas0b2']
[2025-01-16T07:45:10.432+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask extract_data
[2025-01-16T07:45:10.482+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.extract_data manual__2025-01-16T07:45:05.069711+00:00 [running]> on host airflow-scheduler
[2025-01-16T07:45:10.579+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T07:45:05.069711+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T07:45:05.069711+00:00'
[2025-01-16T07:45:10.580+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-16T07:45:10.587+0000] {base.py:84} INFO - Using connection ID 'spark_main' for task execution.
[2025-01-16T07:45:10.589+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /dags/resources/extract.py
[2025-01-16T07:45:10.986+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-01-16T07:45:10.988+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-16T07:45:10.989+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2025-01-16T07:45:10.992+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-16T07:45:12.108+0000] {spark_submit.py:641} INFO - 25/01/16 07:45:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-16T07:45:12.412+0000] {spark_submit.py:641} INFO - python3: can't open file '/dags/resources/extract.py': [Errno 2] No such file or directory
[2025-01-16T07:45:12.421+0000] {spark_submit.py:641} INFO - 25/01/16 07:45:12 INFO ShutdownHookManager: Shutdown hook called
[2025-01-16T07:45:12.423+0000] {spark_submit.py:641} INFO - 25/01/16 07:45:12 INFO ShutdownHookManager: Deleting directory /tmp/spark-9cfdd70f-eaec-436d-9705-bb1f3a21d534
[2025-01-16T07:45:12.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-16T07:45:12.472+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /dags/resources/extract.py. Error code is: 2.
[2025-01-16T07:45:12.477+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL, task_id=extract_data, run_id=manual__2025-01-16T07:45:05.069711+00:00, execution_date=20250116T074505, start_date=20250116T074510, end_date=20250116T074512
[2025-01-16T07:45:12.493+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task extract_data (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /dags/resources/extract.py. Error code is: 2.; 821)
[2025-01-16T07:45:12.527+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-16T07:45:12.552+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-16T07:45:12.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
